package com.WallE.TCMK.POJO;
// Generated 2017-8-29 9:54:56 by Hibernate Tools 4.3.1



/**
 * DoctorInformation generated by hbm2java
 */
public class DoctorInformation  implements java.io.Serializable {


     private int code;
     private String dep;

    public DoctorInformation() {
    }

    public DoctorInformation(int code, String dep) {
       this.code = code;
       this.dep = dep;
    }
   
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }
    public String getDep() {
        return this.dep;
    }
    
    public void setDep(String dep) {
        this.dep = dep;
    }




}


