package com.WallE.TCMK.POJO;
// Generated 2017-8-29 9:54:56 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * RecordId generated by hbm2java
 */
public class RecordId  implements java.io.Serializable {


     private int code;
     private Date date;

    public RecordId() {
    }

    public RecordId(int code, Date date) {
       this.code = code;
       this.date = date;
    }
   
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof RecordId) ) return false;
		 RecordId castOther = ( RecordId ) other; 
         
		 return (this.getCode()==castOther.getCode())
 && ( (this.getDate()==castOther.getDate()) || ( this.getDate()!=null && castOther.getDate()!=null && this.getDate().equals(castOther.getDate()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getCode();
         result = 37 * result + ( getDate() == null ? 0 : this.getDate().hashCode() );
         return result;
   }   


}


