package POJO;
// Generated 2017-8-29 9:54:56 by Hibernate Tools 4.3.1


import java.math.BigDecimal;

/**
 * HealthInfo generated by hbm2java
 */
public class HealthInfo  implements java.io.Serializable {


     private HealthInfoId id;
     private BigDecimal bloodHigh;
     private BigDecimal bloodLow;
     private BigDecimal weight;
     private BigDecimal height;

    public HealthInfo() {
    }

	
    public HealthInfo(HealthInfoId id) {
        this.id = id;
    }
    public HealthInfo(HealthInfoId id, BigDecimal bloodHigh, BigDecimal bloodLow, BigDecimal weight, BigDecimal height) {
       this.id = id;
       this.bloodHigh = bloodHigh;
       this.bloodLow = bloodLow;
       this.weight = weight;
       this.height = height;
    }
   
    public HealthInfoId getId() {
        return this.id;
    }
    
    public void setId(HealthInfoId id) {
        this.id = id;
    }
    public BigDecimal getBloodHigh() {
        return this.bloodHigh;
    }
    
    public void setBloodHigh(BigDecimal bloodHigh) {
        this.bloodHigh = bloodHigh;
    }
    public BigDecimal getBloodLow() {
        return this.bloodLow;
    }
    
    public void setBloodLow(BigDecimal bloodLow) {
        this.bloodLow = bloodLow;
    }
    public BigDecimal getWeight() {
        return this.weight;
    }
    
    public void setWeight(BigDecimal weight) {
        this.weight = weight;
    }
    public BigDecimal getHeight() {
        return this.height;
    }
    
    public void setHeight(BigDecimal height) {
        this.height = height;
    }




}


