package POJO;
// Generated 2017-8-29 9:54:56 by Hibernate Tools 4.3.1



/**
 * Record generated by hbm2java
 */
public class Record  implements java.io.Serializable {


     private RecordId id;
     private String result;

    public Record() {
    }

	
    public Record(RecordId id) {
        this.id = id;
    }
    public Record(RecordId id, String result) {
       this.id = id;
       this.result = result;
    }
   
    public RecordId getId() {
        return this.id;
    }
    
    public void setId(RecordId id) {
        this.id = id;
    }
    public String getResult() {
        return this.result;
    }
    
    public void setResult(String result) {
        this.result = result;
    }




}


