package pojo;
// Generated 2017-8-29 9:54:56 by Hibernate Tools 4.3.1



/**
 * TonguePhoto generated by hbm2java
 */
public class TonguePhoto  implements java.io.Serializable {


     private TonguePhotoId id;
     private String path;

    public TonguePhoto() {
    }

    public TonguePhoto(TonguePhotoId id, String path) {
       this.id = id;
       this.path = path;
    }
   
    public TonguePhotoId getId() {
        return this.id;
    }
    
    public void setId(TonguePhotoId id) {
        this.id = id;
    }
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }




}


