package POJO;
// Generated 2017-8-29 9:54:56 by Hibernate Tools 4.3.1



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private int code;
     private String userAccount;
     private String userType;
     private String password;

    public User() {
    }

	
    public User(int code, String userAccount, String userType) {
        this.code = code;
        this.userAccount = userAccount;
        this.userType = userType;
    }
    public User(int code, String userAccount, String userType, String password) {
       this.code = code;
       this.userAccount = userAccount;
       this.userType = userType;
       this.password = password;
    }
   
    public int getCode() {
        return this.code;
    }
    
    public void setCode(int code) {
        this.code = code;
    }
    public String getUserAccount() {
        return this.userAccount;
    }
    
    public void setUserAccount(String userAccount) {
        this.userAccount = userAccount;
    }
    public String getUserType() {
        return this.userType;
    }
    
    public void setUserType(String userType) {
        this.userType = userType;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }




}


